# Generated by Django 3.0.8 on 2020-08-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('domain', models.CharField(max_length=128)),
                ('client_id', models.CharField(max_length=128)),
                ('client_secret', models.CharField(max_length=128)),
                ('authorize_url', models.CharField(max_length=256)),
                ('access_token_url', models.CharField(max_length=256)),
                ('profile_url', models.CharField(max_length=256)),
                ('scopes', models.CharField(blank=True, max_length=256, null=True)),
                ('email_key', models.CharField(max_length=64)),
                ('profile_url_key', models.CharField(max_length=64)),
                ('photo_url_key', models.CharField(max_length=64)),
                ('full_name_key', models.CharField(blank=True, max_length=64, null=True)),
                ('first_name_key', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name_key', models.CharField(blank=True, max_length=64, null=True)),
                ('name_parser', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'sso_oauth2_client',
                'unique_together': {('domain',)},
            },
        ),
    ]
