# Generated by Django 3.0.8 on 2020-08-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0122_delete_ssoclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('client_id', models.CharField(max_length=128)),
                ('client_secret', models.CharField(max_length=128)),
                ('authorize_url', models.CharField(max_length=256)),
                ('access_token_url', models.CharField(max_length=256)),
                ('profile_url', models.CharField(max_length=256)),
                ('scopes', models.CharField(blank=True, max_length=256, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oauth2_client', to='dashboard.Company')),
            ],
            options={
                'db_table': 'sso_oauth2_client',
            },
        ),
    ]
