# Generated by Django 3.0.8 on 2020-08-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0122_delete_ssoclient'),
        ('oauth2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sso_oauth2_client', to='dashboard.Company'),
        ),
    ]
